# Generated by Django 6.0.6 on 2026-06-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_headlines',
            field=models.BooleanField(default=False),
        ),
    ]
