# Generated by Django 6.0.6 on 2026-07-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bioblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name_plural': 'Sociallinks'},
        ),
        migrations.AddField(
            model_name='sociallink',
            name='plartform_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
