# Generated by Django 6.0.6 on 2026-07-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bioblog', '0002_alter_about_options_alter_sociallink_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about_us',
        ),
        migrations.AddField(
            model_name='about',
            name='about_description',
            field=models.CharField(default='about me', max_length=10000),
        ),
        migrations.AddField(
            model_name='about',
            name='about_heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
