# Generated by Django 6.0.6 on 2026-07-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bioblog', '0003_remove_about_about_us_about_about_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_media_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_name', models.CharField(max_length=100)),
                ('social_media_image', models.ImageField(upload_to='uploads/%Y/%m/%d')),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Social Media',
            },
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
